### ISSUE TITLE
Copy jsonb from postgres to postgres doesn't handle escaped quotes

### ISSUE THREAD

**Issue by kaylon** [mara/mara-db#14]
For a jsonb payload like
`{"text": "Some \"great\" text"}`
the Copy will fail. The copy_to_stdout_command correctly writes the payload as escaped string.
the copy_from_stdin_command however will not recognize. When trying to work around by setting target column to TEXT the double quotes get unescaped.

tried:
* running COPY FROM in CSV mode using ESCAPE '\', but will not easily work due to interference of double quotes in json tokens.

possible solutions:
* maybe? running postgres to postgres via COPY TO STDOUT BINARY | COPY FROM STDIN  BINARY?

Useful hints or workarounds are welcome. I can probably move these imports to postgres_fdw for the time being.

**Comment by martin-loetzsch** [comment]
Ouch. Quoting issues are also the reason why the `Copy` command is not used in schema copying: https://github.com/mara/etl-tools/blob/master/etl_tools/schema_copying.py#L131

That works, but it would be nice to also get it working with `Copy`

**Comment by martin-loetzsch** [comment]
Resolved in https://github.com/mara/mara-db/commit/422c332b09b4e28e19289f0baa27f5102ade9a03
