### ISSUE TITLE
Could not find a version that satisfies the requirement mara-page>=1.3.0 (from mara-db==4.1.0) (from versions: ) No matching distribution found for mara-page>=1.3.0 (from mara-db==4.1.0)

### ISSUE THREAD

**Issue by kingar13** [mara/mara-db#20]
Hello please i need solve of this issues 
Could not find a version that satisfies the requirement mara-page>=1.3.0 (from mara-db==4.1.0) (from versions: )
No matching distribution found for mara-page>=1.3.0 (from mara-db==4.1.0)
i have python 3.6.7 on ubunto

**Comment by martin-loetzsch** [comment]
That should be fixed now. We were previously relying on the [--process-dependency-links](https://github.com/pypa/pip/issues/6162) feature of pip, now we solved it by uploading mara_db to pypi.
