### ISSUE TITLE
breaking constraint BigQuery implementation of copy_from_stdin_command

### ISSUE THREAD

**Issue by hz-lschick** [mara/mara-db#35]
The current BigQuery implementation uses the function `copy_from_stdin_command` to get the `bq load ...` command for a local file without piping in case the `gcloud_gcs_bucket_name` parameter of the `BigQueryDB` is not set. See [here](https://github.com/mara/mara-db/blob/master/mara_db/shell.py#L396-L397)

This is not align with the `copy_from_stdin_command` function name, since it does not use piping. In my business case, I don't need support for this. But in case we want to keep this, I think it should be moved to another function (e.g. `copy _from_file_command`). 

This "workaround" to load local files without using a gcs bucket will cause issues when calling other commands, like  `mara_pipelines.commands.sql.Copy`.

**Comment by martin-loetzsch** [comment]
Hi @hz-lschick , does https://github.com/mara/mara-db/pull/45 fix this for you?

**Comment by hz-lschick** [comment]
Yes 👍
