### ISSUE TITLE
sqsh vs sqlcmd for SQL Server support

### ISSUE THREAD

**Issue by ghost** [mara/mara-db#39]
## Current sqsh implementation
Currently SQL Server is supported via [`sqsh`](https://manpages.debian.org/testing/sqsh/sqsh.1.en.html) which has some disadvantageous:
* does not support named instances
* requires the `GO` command to be written in lowercase, but by default it is case insensitive (`GO`, `Go`, `gO` and `go` should all work)
* requires additional seeding of `;;\n\go` after the sql statement, see [here](https://github.com/mara/mara-db/blob/master/mara_db/shell.py#L118-L120)

## Possible alternative sqlcmd
As alternative, the official Microsoft tool [`sqlcmd`](https://docs.microsoft.com/en-us/sql/tools/sqlcmd-utility?view=sql-server-ver15) (official available for Linux) could be used instead. 

**Sample shell call with piping:** `echo "select 1;" | sqlcmd -S "server" -U "user" -P "password" -i /dev/stdin` ([ref.](https://github.com/microsoft/homebrew-mssql-release/issues/2#issuecomment-682285561))

**Comment by jankatins** [comment]
If that works: yay, no my sqsh and I can finally delete my launchpad account. When I looked into the MS tools, they didn't support "query on stdin, output as csv on stdout". Seems they added it now if the above statement now works :-)... 

A nice way to test it is defining the things locally via a new db name (`class SqlcmdSQLServer(SQLServer): pass` and write the mara integration stuff locally against that new class. I really love the ease of singledispatch for this :-)

An alternative is simply using a small python wrapper around the python DB interface to pyodbc. E.g. sqpy: https://github.com/kfzteile24/sqpy I use that pattern (python wrapper around the python db interface) currently with firebird and athena and it works quite well. But pyodbc was also a pain to setup if I remember correctly :-(

**Comment by hz-lschick** [comment]
Please upvote microsoft feedback ticket [Support reading from stdin for sqlcmd/bcp on *nix platforms](https://feedback.azure.com/d365community/idea/cb9cc4a4-7c25-ec11-b6e6-000d3a4f0da0?q=stdin&page=1) so that we can make this implementation even better and support reading stdin to sql server without dirty hacks.

**Comment by leo-schick** [comment]
MSSQL Tools can now be used optionally via #57.

I close this issue now
