### ISSUE TITLE
Remove timezone parameter for shell commands

### ISSUE THREAD

**Issue by ice1e0** [mara/mara-db#44]
All of the functions in the `shell.py` file have a `timezone` parameter. I would like to challenge this design pattern.

Often you define as database designer in which timezone you want to save datetime data. Often UTC is used in environments where multiple timezones can be used. The conversion from UTC to the client/user timezone then often takes place a) in the receiving client or b) in SQL. In the recent years DBMSs started to add timezone handling via SQL. Samples:
* [PostgreSQL](https://www.enterprisedb.com/postgres-tutorials/postgres-time-zone-explained)
* [Big Query](https://cloud.google.com/bigquery/docs/reference/standard-sql/timestamp_functions#extract)
* [SQL Server](https://docs.microsoft.com/en-us/sql/t-sql/queries/at-time-zone-transact-sql?view=sql-server-ver15)

The timezone parameter is only implemented for postgresql. It looks like that other shell clients do not implement timezone handling. Therefore, I suggest to
* remove the `timezone` parameter from the functions in `shell.py`
* remove the `default_timezone` config
* add a timezone config parameter to the `PostgreSQLDB` config class

With this design the timezone handling is expected to be handled in SQL (or after reading the data). In case someone needs to call `psql` with different timezones, this will be still possible by duplicating the db config. I consider this to be an uncommon use case.

**Comment by hz-lschick** [comment]
Hmm, sounds interesting. In case we want to do that, I would say that should not be done before the next major release. @martin-loetzsch in case you apprive that, I suggest to set it on a milestone for version 5.0

**Comment by jankatins** [comment]
The main problem I see is that for doing copy, the timezone has to match on both the copy to stdin and then copy from stdout. So having mismatched TZ on two DBs will screw it up and therefore IMO the timezone parameter in the `shell.py` functions is correct so that the copy command can set it on both sides.


So IMO it makes more sense to add it to the DBs which currently do not support a timezone parameter during query time so they can error out if the given timezone does not match their configured timezone so you actually do not need to do the TZ handling in the query.

**Comment by martin-loetzsch** [comment]
If you copy a timestamp without timezone information such as `2021-03-08 22:26:23` into a timestamp with timezone field in PG, then it depends on the time zone setting of the client how the string is interpreted. 

But you are right, using TIMESTAMP at timezone creates the same effect.

This feature is a relict from the past where there were a lot different databases running in non- UTC timestamps.

So I'd be happy to accept a PR on this.

**Comment by ice1e0** [comment]
@martin-loetzsch I merged this now into branch v5.0. I did not merge this into master since it might break existing installations.
